<?php
$z[0]=Array("global","(@me==1)? @me=\"<a href=\"[field:typeurl/]' title='[field:fulltitle/]' target='_blank'>\r\n									[field:title /]</a>\":@me=\"\";",0,181);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",222,264);
$z[1][4]=array();
$z[1][4]['function']="GetDateMK(@me)";
$z[2]=Array("typeurl","",395,411);
$z[2][4]=array();
$z[3]=Array("fulltitle","",420,438);
$z[3][4]=array();
$z[4]=Array("title","",467,482);
$z[4][4]=array();

?>