<?php
$z[0]=Array("global","(@me==1)? @me=\"[field:pubdate function=\"GetDateMK(@me)\":@me=\"\";",0,120);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",161,203);
$z[1][4]=array();
$z[1][4]['function']="GetDateMK(@me)";
$z[2]=Array("typeurl","",334,350);
$z[2][4]=array();
$z[3]=Array("fulltitle","",359,377);
$z[3][4]=array();
$z[4]=Array("title","",406,421);
$z[4][4]=array();

?>