<?php
$z[0]=Array("global","(@me==1)? '<li><span class=\"date\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n								<img src=\"http://www.jssjcwsxh.com/Public/Home/img/dian.png\" width=\"5px\" height=\"5px\" alt=\"\" />\r\n								<a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">\r\n									[field:title /]</a>\r\n							</li>':@me=\"\";",0,378);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",419,461);
$z[1][4]=array();
$z[1][4]['function']="GetDateMK(@me)";
$z[2]=Array("typeurl","",592,608);
$z[2][4]=array();
$z[3]=Array("fulltitle","",617,635);
$z[3][4]=array();
$z[4]=Array("title","",664,679);
$z[4][4]=array();

?>