<?php
$z[0]=Array("global","(@me==1)? <li><span class=\"date\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n								<img src=\"http://www.jssjcwsxh.com/Public/Home/img/dian.png\" width=\"5px\" height=\"5px\" alt=\"\" />\r\n								<a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">\r\n									[field:title /]</a>\r\n							</li>:@me=\"\";",0,376);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",417,459);
$z[1][4]=array();
$z[1][4]['function']="GetDateMK(@me)";
$z[2]=Array("typeurl","",590,606);
$z[2][4]=array();
$z[3]=Array("fulltitle","",615,633);
$z[3][4]=array();
$z[4]=Array("title","",662,677);
$z[4][4]=array();

?>