<?php
$z[0]=Array("global","(@me==1)? @me=\"<li><span class=\"date\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n								<img src=\"http://www.jssjcwsxh.com/Public/Home/img/dian.png\" width=\"5px\" height=\"5px\" alt=\"\" />\r\n								<a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">\r\n									[field:title /]</a>\r\n							</li>\":@me=\"\";",0,382);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";

?>