<?php
$z[0]=Array("global","(@me==1)? @me=\"class=on\":@me=\"\";",0,89);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",130,172);
$z[1][4]=array();
$z[1][4]['function']="GetDateMK(@me)";
$z[2]=Array("typeurl","",303,319);
$z[2][4]=array();
$z[3]=Array("fulltitle","",328,346);
$z[3][4]=array();
$z[4]=Array("title","",375,390);
$z[4][4]=array();

?>