<?php
$z[0]=Array("arcurl","",39,54);
$z[0][4]=array();
$z[1]=Array("fulltitle","",63,81);
$z[1][4]=array();
$z[2]=Array("title","",99,184);
$z[2][4]=array();
$z[2][4]['function']="( strlen(\"@me\")>40 ? cn_substr(\"@me\",40).\"...\" : \"@me\" )";
$z[3]=Array("info","",206,290);
$z[3][4]=array();
$z[3][4]['function']="( strlen(\"@me\")>84 ? cn_substr(\"@me\",84).\"...\" : \"@me\" )";
$z[4]=Array("arcurl","",299,314);
$z[4][4]=array();

?>