[field:global name=autoindex runphp="yes"](@me==1)? @me="<a href="[field:typeurl/]" title="[field:fulltitle/]" target="_blank">
									[field:title /]</a>":@me="";[/field:global]
							
							<li><span class="date">[field:pubdate function="GetDateMK(@me)"/]</span>
								<img src="http://www.jssjcwsxh.com/Public/Home/img/dian.png" width="5px" height="5px" alt="" />
								<a href="[field:typeurl/]" title="[field:fulltitle/]" target="_blank">
									[field:title /]</a>
							</li>