<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",109,146);
$z[1][4]=array();
$z[1][4]['filename']="header.htm";
$z[2]=Array("channel","\r\n					<span style=\"font-size:14px;\"><a href=\"[field:typeurl/]\">[field:typename/]</a></span> ",292,425);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[3]=Array("field","",526,555);
$z[3][4]=array();
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n					<div class=\"sub_show_content\">\r\n						<li>\r\n							<a href=\"[field:arcurl/]\" target=\"_self\"><span class=\"floatright fontnote\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n								<span class=\"limit\"><a href=\"[field:arcurl/]\"  target=\"_self\">[field:title/]</a></span></a>\r\n						</li>\r\n					</div>\r\n					",561,914);
$z[4][4]=array();
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",979,1057);
$z[5][4]=array();
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1191,1228);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>