<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",109,146);
$z[1][4]=array();
$z[1][4]['filename']="header.htm";
$z[2]=Array("global","",332,387);
$z[2][4]=array();
$z[2][4]['name']="keyword";
$z[2][4]['function']="RemoveXSS(@me)";
$z[3]=Array("field","",495,524);
$z[3][4]=array();
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n					<div class=\"sub_show_content\">\r\n						<li>\r\n							<a href=\"[field:arcurl/]\" target=\"_self\"><span class=\"floatright fontnote\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n								<span class=\"limit\"><a href=\"[field:arcurl/]\"  target=\"_self\">[field:title/]</a></span></a>\r\n						</li>\r\n					</div>\r\n					",537,890);
$z[4][4]=array();
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",955,1033);
$z[5][4]=array();
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1167,1204);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>